services:
  cyberpunknutrition:
    image: cyberpunknutrition
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/cyberpunk_nutrition
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server/index.js"]
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongo_data:
